on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

name: Generate TypeScript SDK

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: 'npm'
      - name: Install OpenAPI Generator CLI
        run: npm install @openapitools/openapi-generator-cli
      - name: Set OpenAPI Generator version
        run: ./node_modules/\@openapitools/openapi-generator-cli/main.js version-manager set 6.0.1
      - name: Generate SDK Client
        run: ./node_modules/\@openapitools/openapi-generator-cli/main.js generate -g typescript-axios --additional-properties=npmName=vrchat,supportsES6=true --git-user-id=Robotex --git-repo-id=VRChat-API -o ./sdk -i https://raw.githubusercontent.com/vrchatapi/specification/gh-pages/openapi.yaml --http-user-agent="vrchatapi-javascript"
      - name: Check version number
        run: |
          echo "spec_version=$(grep "version" ./package.json | cut -d "\"" -f 4)" >> $GITHUB_ENV
      - name: Print version number
        run: echo ${{ env.spec_version }}
      - name: Deploy SDK
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: typescript-axios
          folder: ./sdk
          commit-message: "Upgrade SDK to spec ${{ env.spec_version }}"
